README.md

Created following files
merge this, brah @iSyn

added basic file structure and started readme

---

db/schema.sql
db/seeds.sql

sql file w/ tables and seed file w/ dummy data

Mike branch1

---

package.json

configured package.json

---

routes/home.js
server.js

synclair i just set up a simple server and home route that is up and running

set up simple server

---

routes/api.js
server.js

added api route and its working

set up api route

---

models/questions.js
models/users.js

updated model function

---

package.json

added dotenv

---

README.md

please merge @iSyn thank you!!

added component structure to readme

---

model/users.js

had to change query function on student...it now works completely

---

model/users.js

had to fix query so it doesnt show user password

api was showing user passwords, so i went in and fixed that

---

db/schema.sql
db/seeds.sql
model/users.js
server.js
src/components/App/Modals/SignUpModal/SignUpModal.jsx

added app.use(bodyParser.urlencoded()) and now things are working more
working on some more createUser, edited schema a bit
did a bunch of shit, working server side user creation!!!

UGHHHHHHH 

---

model/questions.js
routes/api.js
src/components/App/App.jsx
src/components/App/Modals/AskQuestionsModal/AskQuestionsModal.jsx

please add this...the create new question and save to db is working

'add new function to save to db'

---

model/questions.js
model/users.js
routes/api.js
routes/users.js
src/components/App/App.jsx

added comments in certain sections

added comments

---

model/questions.js
src/components/App/App.jsx
src/components/App/MainBody/MainBody.jsx
src/components/App/MainBody/QuestionsContainer/Questions/Questions.jsx
src/components/App/MainBody/QuestionsContainer/QuestionsContainer.jsx

Pending to finish 
please merge @iSyn 
Thank you!

Render questions from static state

---

src/components/App/App.jsx
src/components/App/MainBody/MainBody.jsx
src/components/App/MainBody/QuestionsContainer/QuestionsContainer.jsx

Please merge @iSyn 
Thank you!

Render questions with fetch to API working

---

model/questions.js
src/components/App/App.jsx

Please merge @iSyn 
thank you!

changes to GET ALL QUESTIONS

---

server.js
src/components/App/App.jsx
webpack.config.js

> NOTE: this is incomplete but has not broken project
TODO: 
Please merge 
@iSyn 
thank you

Socket kind of working

---

model/questions.js
server.js
src/components/App/App.jsx

fucking sockets are hearing each other...now need it to grab data from db to render

socket sending out ping and hearing it

---

model/questions.js
package.json
routes/api.js
server.js
src/components/App/App.jsx
src/components/App/MainBody/MainBody.jsx
src/components/App/MainBody/QuestionsContainer/Questions/Questions.jsx
src/components/App/MainBody/QuestionsContainer/QuestionsContainer.jsx

likes render without error in console

Renderlike2

---

package.json
scripts/deployment_cleanup.sh
scripts/deployment_react.sh
server.js

Taka package

---

db/schema.sql
model/questions.js
server.js

psql and schema changes

---

package.json
scripts/deployment_cleanup.sh

change package.json and correct script
